### ISSUE TITLE
Failed to start plugin

### ISSUE THREAD

**Issue by KuzmaTolyanuch** [koush/scrypted-home-assistant#12]
Hi, 
Is this plugin suppose to work with scrypted version 0.0.116 ? I see that there was no updates for few years.
I'm runnning scrypted in docker on rasspberry pi 4. Image tag 16. 
Getting error "Failed to load plugin"

Console log:

`
starting plugin @scrypted/home-assistant 0.0.8
failure loadZip TypeError: Cannot read properties of null (reading 'getData')
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:442:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:471:37)
 `
 Looking forward to your response. Thank in advance.

**Comment by dehness** [comment]
Yup. Same problem:

```
starting plugin @scrypted/home-assistant 0.0.8
failure loadZip TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:481:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:483:37)
```

Hopefully the developer takes a look at some point.
